version: '3'
services:
  php:
    container_name: "train-php-cli"
    build: ./docker/php/
    volumes:
      - .:/var/www/project
    ports:
      - 8080:80
    working_dir: /var/www/project
    command: ["php", "-S", "0.0.0.0:80", "-t", "./public"]
  redis:
    image: redis:latest
    container_name: "train-redis"
  mongo:
    image: mongo:latest
    container_name: "train-mongo"
  rediscommander:
    container_name: "train-redis-commander"
    image: rediscommander/redis-commander:latest
    ports:
      - 9083:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
  mongoexpress:
    container_name: "train-mongo-express"
    image: mongo-express:latest
    ports:
      - 9084:8081
    depends_on:
      - mongo
